# Generated by Django 4.0.6 on 2022-08-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_detail',
            field=models.CharField(default='detail', max_length=200),
        ),
    ]
