# Generated by Django 4.0.4 on 2022-08-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_detail',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
