# Generated by Django 4.1 on 2022-08-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_price_jumia_alter_product_price_kara_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='name', max_length=20),
        ),
    ]
