# Generated by Django 4.0.4 on 2022-08-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_comment_name_id_comment_name'),
        ('products', '0008_alter_comment_product'),
    ]

    operations = [
    ]
