# Generated by Django 4.0.4 on 2022-08-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default-product.png', upload_to='images/'),
        ),
    ]
